language: node_js
node_js:
  - 'stable'
cache:
directories:
  - 'node_modules'
env:
  global:
    - CODECLIMATE_REPO_TOKEN=d58ca6085dce614b1d96579208063d53a987fe46b061887b13a6c4317155c480
install:
  - npm install
script:
  - npm test
after_success: npm run coverage
